### ISSUE TITLE
Error parsing timestamp

### ISSUE THREAD

**Issue by lumjjb** [goneall/spdx-to-osv#6]
Error parsing timestamp:
```
Error converting SPDX file to OSV.
com.sourceauditor.spdx_to_osv.SpdxToOsvException: Error reading the SPDX input file
	at com.sourceauditor.spdx_to_osv.Main.spdxToOsv(Main.java:472)
	at com.sourceauditor.spdx_to_osv.Main.spdxToOsv(Main.java:245)
	at com.sourceauditor.spdx_to_osv.Main.main(Main.java:174)
Caused by: org.spdx.library.InvalidSPDXAnalysisException: Invalid date format: Text '2021-16-06T13:41:24Z' could not be parsed at index 0
	at org.spdx.library.model.SpdxCreatorInformation.setCreated(SpdxCreatorInformation.java:137)
	at org.spdx.tag.BuildDocument.buildDocumentProperties(BuildDocument.java:637)
	at org.spdx.tag.BuildDocument.buildDocument(BuildDocument.java:422)
	at org.spdx.tag.HandBuiltParser.data(HandBuiltParser.java:100)
	at org.spdx.tagvaluestore.TagValueStore.deSerialize(TagValueStore.java:88)
	at com.sourceauditor.spdx_to_osv.Main.spdxToOsv(Main.java:469)
	... 2 more
```

Small input file (from `curl -L https://sbom.k8s.io/v1.21.2/source`)
```
SPDXVersion: SPDX-2.2
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: kubernetes-v1.21.2
DocumentNamespace: https://k8s.io/sbom/source/v1.21.2
Creator: Tool: k8s.io/release/pkg/spdx
Created: 2021-16-06T13:41:24Z
```

**Comment by goneall** [comment]
Took a bit to figure this out - but the error is the month number is 16 - which is > 12 months allowed.

**Comment by goneall** [comment]
I'm going to close this since it is an invalid timestamp.

BTW - the error could be improved - but that would be a change to the [SPDX Java Library](https://github.com/spdx/spdx-java-library)
